[secrets]
PINECONE_API_KEY = "1e768c11-49a6-4d79-b238-10ca5a6c92e9"
OPENAI_API_KEY = "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"
